### ISSUE TITLE
Issue on Library Path

### ISSUE THREAD

**Issue by kenalbert11** [iTeam-co/python-telegram#2]
Hi.

I want to use this library but i just cant seem to start using it because of an issue on library path

**Traceback (most recent call last):
  File "testing1.py", line 10, in <module>
    client = Telegram(api_id=api_id, api_hash=api_hash, phone=phone_number, database_encryption_key=dbenc)
TypeError: __init__() missing 1 required positional argument: 'library_path'**

If ever this library is still active, this can be really useful.

Thanks!

**Comment by WebShark025** [comment]
Good day to you
We're trying to make this active again.

You have to build tdlib and give its absolute path in library_path variable.
Follow https://tdlib.github.io/td/build.html for instructions on  how to build tdlib.
